import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

const SITE_COPY = {
  youtube: {
    blurb: "Full-window theater, denser feeds, frosted player chrome, and quieter navigation.",
    hosts: "`youtube.com`",
  },
  github: {
    blurb: "Immersive header search, glass surfaces, and hover-revealed sidebars.",
    hosts: "`github.com`",
  },
  google: {
    blurb: "Search-bar glass, immersive focus, and calmer results chrome. Gmail, Docs, and other Google apps are left alone.",
    hosts: "`google.com` · country search TLDs",
  },
  duckduckgo: {
    blurb: "Frosted panels, immersive search, and a cleaner homepage.",
    hosts: "`duckduckgo.com`",
  },
};

function extractConstArray(source, name) {
  const needle = `const ${name} = [`;
  const start = source.indexOf(needle);
  if (start < 0) throw new Error(`Could not find ${name}`);
  const bracket = source.indexOf("[", start);
  let depth = 0;
  for (let i = bracket; i < source.length; i++) {
    const ch = source[i];
    if (ch === "[") depth += 1;
    else if (ch === "]") {
      depth -= 1;
      if (depth === 0) return source.slice(bracket, i + 1);
    }
  }
  throw new Error(`Unclosed array for ${name}`);
}

function evalArray(source, replacements = {}) {
  let body = source;
  for (const [from, to] of Object.entries(replacements)) {
    body = body.replaceAll(from, to);
  }
  return Function(`"use strict"; return (${body});`)();
}

function badge(label, message, color, extra = "") {
  const encode = (value) => encodeURIComponent(value).replaceAll("-", "--");
  return `![${label}](https://img.shields.io/badge/${encode(label)}-${encode(message)}-${color}?style=for-the-badge&labelColor=1c1a24${extra})`;
}

function featureTable(features) {
  const rows = features
    .map((feature) => {
      const on = feature.defaultEnabled !== false;
      return `| **${feature.title}** | ${feature.description} | ${on ? "On" : "Off"} |`;
    })
    .join("\n");
  return `| Mod | What it does | Default |\n|-----|--------------|---------|\n${rows}`;
}

function groupedFeatureTables(features, categories) {
  const used = new Set(features.map((feature) => feature.category));
  const blocks = [];
  for (const category of categories) {
    if (!used.has(category.id)) continue;
    const group = features.filter((feature) => feature.category === category.id);
    blocks.push(`#### ${category.title}\n\n${featureTable(group)}`);
  }
  return blocks.join("\n\n");
}

function subsettingTable(items) {
  const rows = items
    .map((item) => `| **${item.title}** | ${item.description} |`)
    .join("\n");
  return `| Setting | Effect |\n|---------|--------|\n${rows}`;
}

function siteCard(site, count) {
  const copy = SITE_COPY[site.id] ?? { blurb: "", hosts: site.hostnames.join(", ") };
  return `<td width="25%" valign="top" align="center">
<a href="#${site.id}">
<img src="docs/sites/${site.id}.svg" width="88" alt="${site.title}" />
</a>
<br/>
<strong>${site.title}</strong>
<br/>
<sub>${count} mods · ${copy.hosts}</sub>
</td>`;
}

function buildReadme({ version, sites, features, categories, theater, feed }) {
  const total = features.length;
  const siteCount = sites.length;
  const bySite = Object.fromEntries(
    sites.map((site) => [site.id, features.filter((feature) => (feature.site ?? "youtube") === site.id)])
  );

  const siteRow = sites.map((site) => siteCard(site, bySite[site.id].length)).join("\n");

  const siteSections = sites
    .map((site) => {
      const copy = SITE_COPY[site.id] ?? { blurb: "", hosts: site.hostnames.join(", ") };
      const list = bySite[site.id];
      return `### <img src="docs/sites/${site.id}.svg" width="36" align="absmiddle" alt="" /> ${site.title}

${copy.blurb}

${groupedFeatureTables(list, categories)}`;
    })
    .join("\n\n");

  return `<!-- Generated by scripts/generate-readme.mjs from FEATURE_META / SITE_META. Run: npm run readme -->

<div align="center">
  <img src="docs/banner.svg" width="880" alt="ChroMods — Chromium theming mods" />
  <br/>
  <img src="docs/divider.svg" width="560" alt="" />
  <br/><br/>

  ${badge("Version", `v${version}`, "ff8f6b")}
  ${badge("Manifest", "V3", "ff4f6e", "&logo=googlechrome&logoColor=white")}
  ${badge("Sites", String(siteCount), "ffd9c4")}
  ${badge("Mods", String(total), "8b8b9a")}
  ${badge("License", "MIT", "3a3a48")}

  <p>
    <strong>ChroMods</strong> is a Chrome MV3 extension that ports
    <a href="https://github.com/sameerasw/my-internet">sameerasw/my-internet</a>
    website theming to Chromium — glass, blur, and quieter chrome for the sites you actually live in.
  </p>
</div>

## Supported sites

The popup detects the active tab and surfaces that site's mods first. Everything else stays in a compact list underneath.

<table>
  <tr>
${siteRow}
  </tr>
</table>

## Features

${siteSections}

## Install

1. Clone this repo
2. Open \`chrome://extensions\`
3. Enable **Developer mode**
4. **Load unpacked** → select the repo root
5. Reload any open YouTube, GitHub, Google Search, or DuckDuckGo tabs

## Popup

Settings are grouped by **site**. The active tab is detected automatically. Each site's mods sit in animated, collapsible categories such as **Search**, **Home feed**, **Navigation**, **Appearance**, **Player**, and **Live & comments**. Disruptive mods default to off.

### Theater subsettings

${subsettingTable(theater)}

### Feed layout subsettings

${subsettingTable(feed)}

## Dev

\`\`\`bash
npm install          # playwright for e2e
npm test             # manifest, CSS compatibility, and wiring
npm run test:e2e     # popup UI, theater geometry, and YouTube injection
npm run readme       # regenerate this README from live feature metadata
\`\`\`

## Structure

\`\`\`
manifest.json          MV3 config
scripts/               background, content, popup, sites, and icon JavaScript
popup/                 dark settings panel markup and styles
icons/                 extension icon (SVG source + PNG sizes)
docs/                  README banner and site artwork
styles/                per-feature CSS modules
tests/                 node:test + playwright e2e
\`\`\`

## Notes

- Chromium only (\`:has()\`, \`scale\`, \`backdrop-filter\` with \`-webkit-\` prefix)
- Movable live chat stores its position and opacity in \`chrome.storage.local\`
- Zen's browser-window transparency mods are intentionally excluded — Chromium cannot expose the browser chrome backdrop to page CSS
- Site DOM changes may break selectors — report issues on GitHub
- Settings sync via \`chrome.storage.sync\` under key \`chroModsSettings\`

## License

MIT — CSS derived from [my-internet](https://github.com/sameerasw/my-internet) (MIT)
`;
}

const popupSrc = fs.readFileSync(path.join(root, "scripts/popup.js"), "utf8");
const sitesSrc = fs.readFileSync(path.join(root, "scripts/sites.js"), "utf8");
const manifest = JSON.parse(fs.readFileSync(path.join(root, "manifest.json"), "utf8"));

const features = evalArray(extractConstArray(popupSrc, "FEATURE_META"), {
  FEED_SUBSETTINGS: "[]",
  THEATER_SUBSETTINGS: "[]",
}).map((feature) => ({ ...feature, site: feature.site ?? "youtube" }));

const sites = evalArray(extractConstArray(sitesSrc, "SITE_META"), {
  GOOGLE_SEARCH_HOST: "null",
});
const categories = evalArray(extractConstArray(popupSrc, "CATEGORY_META"));
const theater = evalArray(extractConstArray(popupSrc, "THEATER_SUBSETTINGS"));
const feed = evalArray(extractConstArray(popupSrc, "FEED_SUBSETTINGS"));

const readme = buildReadme({
  version: manifest.version,
  sites,
  features,
  categories,
  theater,
  feed,
});

const readmePath = path.join(root, "README.md");
const check = process.argv.includes("--check");

if (check) {
  const existing = fs.readFileSync(readmePath, "utf8");
  if (existing !== readme) {
    console.error("README.md is stale. Run npm run readme");
    process.exit(1);
  }
  console.log(`README.md is up to date (${features.length} mods across ${sites.length} sites, v${manifest.version})`);
} else {
  fs.writeFileSync(readmePath, readme);
  console.log(`Wrote README.md (${features.length} mods across ${sites.length} sites, v${manifest.version})`);
}
