import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

const SITE_COPY = {
  youtube: { hosts: "youtube.com" },
  github: { hosts: "github.com" },
  google: { hosts: "google.com and country search TLDs" },
  gmail: { hosts: "mail.google.com" },
  gemini: { hosts: "gemini.google.com" },
  duckduckgo: { hosts: "duckduckgo.com" },
  x: { hosts: "x.com, twitter.com" },
  twitch: { hosts: "twitch.tv" },
};

function extractConstArray(source, name) {
  const needle = `const ${name} = [`;
  const start = source.indexOf(needle);
  if (start < 0) throw new Error(`Could not find ${name}`);
  const bracket = source.indexOf("[", start);
  let depth = 0;
  for (let i = bracket; i < source.length; i++) {
    const ch = source[i];
    if (ch === "[") depth += 1;
    else if (ch === "]") {
      depth -= 1;
      if (depth === 0) return source.slice(bracket, i + 1);
    }
  }
  throw new Error(`Unclosed array for ${name}`);
}

function evalArray(source, replacements = {}) {
  let body = source;
  for (const [from, to] of Object.entries(replacements)) {
    body = body.replaceAll(from, to);
  }
  return Function(`"use strict"; return (${body});`)();
}

function featureTable(features) {
  const rows = features
    .map((feature) => {
      const on = feature.defaultEnabled !== false;
      return `| **${feature.title}** | ${feature.description} | ${on ? "On" : "Off"} |`;
    })
    .join("\n");
  return `| Mod | What it does | Default |\n|-----|--------------|---------|\n${rows}`;
}

function siteIcon(site, size = 20) {
  return `<img src="docs/sites/${site.id}.svg" width="${size}" height="${size}" alt="" />`;
}

function siteDisplayName(site) {
  return site.id === "google" ? "Google Search" : site.title;
}

function siteListPhrase(sites) {
  const names = sites.map(siteDisplayName);
  if (names.length <= 1) return names[0] || "";
  if (names.length === 2) return `${names[0]} and ${names[1]}`;
  return `${names.slice(0, -1).join(", ")}, and ${names[names.length - 1]}`;
}

function buildReadme({ version, sites, features }) {
  const bySite = Object.fromEntries(
    sites.map((site) => [site.id, features.filter((feature) => (feature.site ?? "youtube") === site.id)])
  );

  const siteRows = sites
    .map((site) => {
      const copy = SITE_COPY[site.id] ?? { hosts: site.hostnames.join(", ") };
      const count = bySite[site.id].length;
      return `| ${siteIcon(site)} | [${site.title}](#${site.id}) | ${count} | ${copy.hosts} |`;
    })
    .join("\n");

  const siteSections = sites
    .map((site) => {
      const list = bySite[site.id];
      let extra = "";
      if (site.id === "google") {
        extra = "\n\nApplies to Search only — Gmail, Docs, and other Google apps are left alone.";
      }
      return `### ${siteIcon(site, 22)} ${site.title}\n\n${featureTable(list)}${extra}`;
    })
    .join("\n\n");

  const sitesPhrase = siteListPhrase(sites);

  return `<!-- Generated by scripts/generate-readme.mjs from FEATURE_META / SITE_META. Run: npm run readme -->

<div align="center">
  <img src="icons/icon.svg" width="72" height="72" alt="ChroMods" />
  <h1>ChroMods</h1>
  <p>Chrome MV3 theming mods for ${sitesPhrase}.<br/>Styles adapted from <a href="https://github.com/sameerasw/my-internet">my-internet</a>.</p>
  <p>
    <img alt="Version" src="https://img.shields.io/badge/v${version}-111111?label=version" />
    <img alt="Manifest V3" src="https://img.shields.io/badge/MV3-4285F4?logo=googlechrome&logoColor=white" />
    <img alt="License" src="https://img.shields.io/badge/license-MIT-3a3a48" />
  </p>
</div>

The popup detects the active tab and shows that site's mods first. Search the header to jump to a site or mod. A moon/sun toggle can force dark mode on **any website** (Dark Reader engine), with per-site brightness, contrast, sepia, and grayscale in Settings. Sites that already ship a native dark theme are left alone by default. Keyboard shortcuts live in the same settings panel. Unsupported sites get a compact tag and a **Request styling** action that opens a GitHub issue (or an existing one) on this repo.

| | Site | Mods | Hosts |
| :---: | --- | ---: | --- |
${siteRows}

## Features

${siteSections}

## Install

1. Clone this repo → \`chrome://extensions\` → **Developer mode** → **Load unpacked** → repo root
2. Reload any open ${sitesPhrase} tabs

## Dev

\`\`\`bash
npm install          # playwright for e2e
npm test             # manifest, CSS compatibility, and wiring
npm run test:e2e     # popup UI, theater geometry, and YouTube injection
npm run readme       # regenerate this README from live feature metadata
\`\`\`

Chromium only. Zen browser-window transparency is excluded because Chromium cannot expose the chrome backdrop. Settings sync under \`chroModsSettings\`.

## License

MIT — CSS derived from [my-internet](https://github.com/sameerasw/my-internet) (MIT). Dark mode engine from [Dark Reader](https://github.com/darkreader/darkreader) (MIT).
`;
}

const popupSrc = fs.readFileSync(path.join(root, "scripts/popup.js"), "utf8");
const sitesSrc = fs.readFileSync(path.join(root, "scripts/sites.js"), "utf8");
const manifest = JSON.parse(fs.readFileSync(path.join(root, "manifest.json"), "utf8"));

const features = evalArray(extractConstArray(popupSrc, "FEATURE_META"), {
  FEED_SUBSETTINGS: "[]",
  THEATER_SUBSETTINGS: "[]",
}).map((feature) => ({ ...feature, site: feature.site ?? "youtube" }));

const sites = evalArray(extractConstArray(sitesSrc, "SITE_META"), {
  GOOGLE_SEARCH_HOST: "null",
});

const readme = buildReadme({
  version: manifest.version,
  sites,
  features,
});

const readmePath = path.join(root, "README.md");
const check = process.argv.includes("--check");

if (check) {
  const existing = fs.readFileSync(readmePath, "utf8");
  if (existing !== readme) {
    console.error("README.md is stale. Run npm run readme");
    process.exit(1);
  }
  console.log(`README.md is up to date (${features.length} mods across ${sites.length} sites, v${manifest.version})`);
} else {
  fs.writeFileSync(readmePath, readme);
  console.log(`Wrote README.md (${features.length} mods across ${sites.length} sites, v${manifest.version})`);
}
